### ISSUE TITLE
Recortar en chnsCompute

### ISSUE THREAD

**Issue by jorgevelap** [RoboticsLabURJC/2017-tfm-jorge_vela#10]

**Comment by jorgevelap** [comment]
La función chnsCompute está finalizada, pero hay algo que no consigo encontrar.
En la función de Matlab, al principio llama a crop, que lo único que hace es quitar los últimos pixeles sobrantes. No se porque, aunque comparo las imágenes y veo que esto es así, los siguientes resultados cambian bastante. Un ejemplo es el siguiente:

![ChnsCompute_M_noCrop](https://user-images.githubusercontent.com/16937271/81089226-6116ac00-8efc-11ea-9ca2-2ede14169d48.PNG)

Pero si llamo a crop, el resultado cambia:
![ChnsCompute_M_Crop](https://user-images.githubusercontent.com/16937271/81089247-6aa01400-8efc-11ea-88c9-db1853592bc9.PNG)

Aunque en la M es un cambio poco significativo, como los otros resultados dependen de estos obtenidos aumenta algo dicha variación

**Comment by jmbuena** [comment]
Creo que esto ya lo hemos implementado correctamente y además hemos pasado esta función al extractor de canales ACF y al LDCF.
