### ISSUE TITLE
Comprobar que convTri está correctamente implementada

### ISSUE THREAD

**Issue by jmbuena** [RoboticsLabURJC/2017-tfm-jorge_vela#12]
Se trata de generar casos de prueba desde Matlab y comprobar que funciona como debe en la implementación nueva usando OpenCV.

**Comment by jmbuena** [comment]
La idea es pasar imágenes sintéticas generadas, por ejemplo con números en secuencia, y comprobar que Matlab y nuestra implementación dan el mismo resultado. Por otro lado también es importante comprobarlo en alguna imagen real (pequeña).

**Comment by jorgevelap** [comment]
Se han realizado varias pruebas de convTri, tanto con imágenes sintéticas como con imágenes reales.
Se ha comparado con el proceso de matlab, y para que diera el mismo resultado había que añadir bordes antes de llamar a filer2D, con cv::BORDER_REFLECT como parámetro y el tamaño del kernel en el padding. Tras ello, retornar solo la parte central de la imagen.
Todas las pruebas realizadas aceptan un error menor a una diferencia de 0.01 por pixel.

**Comment by jmbuena** [comment]
El commit fdd84d158226cc53b535efc2806f7226fc9782ff cierra este issue.
