### ISSUE TITLE
Implementar completamente el ImgResample de P. Dollar

### ISSUE THREAD

**Issue by jmbuena** [RoboticsLabURJC/2017-tfm-jorge_vela#14]
Falta el uso de los lambda en el redimensionado. Además deberíamos generar los tests para comprobar completamente que el resultado es correcto con imágenes sintéticas y con una imagen natural al menos.

**Comment by jorgevelap** [comment]
Se ha añadido el parametro "norm" para realizar el uso de los lambda en el redimensionado.  Al realizar pruebas con esto, el tiene un parámetro llamado "method" en el que indica que tipo de interpolación va a realizar. Generalmente utiliza bilineal con antialiasing (INTER_AREA) aunque en algunos casos utiliza bilineal sin antialiasing (INTER_LINEAR). Se ha añadido este parámetro para poder elegir, poniendo por defecto antialiasing.

**Comment by jmbuena** [comment]
Completado con el commit 98d2ee734823eaf5c30325ae6aabc00935b4afc0.
