### ISSUE TITLE
Generar tests para ChannelsExtractorLDCF

### ISSUE THREAD

**Issue by jmbuena** [RoboticsLabURJC/2017-tfm-jorge_vela#15]
Mover el test que teníamos de badacostFilters en ChannelsPyramid a un test TestChannelsExtractorLDCF. 

Generar todos los tests posibles para ver si tenemos exáctamente el mismo resultado que en Matlab.

**Comment by jorgevelap** [comment]
He realizado los primeros test para ChannelsExtractorLDCF. 
Los que he subido son imágenes sintéticas para la función extractFeaturesFromACF. Tengo que completar estos tests pero estaba haciendo algo mal y no se como arreglarlo. He hecho estos tests para ir comprobando esta función y la diferencia de los valores es muy pequeña.

**Comment by jmbuena** [comment]
En estos test quizá deberíamos quedarnos en algo sencillo. Por ejemplo, utilizar una imagen natural y ya está. Date cuenta que el test importante en el de ACF y ese lo hacemos muy completo.

Por otra parte, los tests deben de ser no muy lentos. El proposito es comprobar que no hemos roto nada con algún cambio que hagamos. Eso es fundamental para ir desarrollado, ejecutando tests y seguir confiando en que todo funciona.

**Comment by jmbuena** [comment]
Terminado en b90da203f7fb8fdeac77af82e62ef833e2126c65 y 269e4fb5d286e1ef8a870d64ed91770626b7f8c1.
