### ISSUE TITLE
Usar código matlab para detección multiclase con BAdaCost

### ISSUE THREAD

**Issue by jmbuena** [RoboticsLabURJC/2017-tfm-jorge_vela#2]
En este caso hay que usar el toolbox de Matlab modificado con [BadaCost.](https://github.com/jmbuena/toolbox.badacost.public).

Aquí el script de detección es [acfDetectBadacost](https://github.com/jmbuena/toolbox.badacost.public/blob/master/detector/acfDetectBadacost.m). Este script llama a:

1) chnsPyramid
2) Llama para cada escala al código C++ para detección en ventana deslizante [acfDetectBadacostTrees1](https://github.com/jmbuena/toolbox.badacost.public/blob/master/detector/private/acfDetectBadacostTrees1.cpp). 

Un ejemplo para jugar con la detección BAdaCost es el [detector de coches](https://github.com/jmbuena/toolbox.badacost.kitti.public/blob/master/main.m).

**Comment by jorgevelap** [comment]
He intentado ejecutar el script del detector de coches pero me daba todo el rato el siguiente error:
Undefined function 'chnsPyramid' for input arguments of type 'struct'.
Error in acfDetect>acfDetectImg (line 91)
P=chnsPyramid(I,pPyramid);

Error in acfDetect (line 41)
if(~multiple), bbs=acfDetectImg(I,detector); else

Error in apply_detector_to_imgs (line 54)
      bbs = acfDetect(I, badacost_detector);

Error in main (line 98)
apply_detector_to_imgs(badacost_detector, …


No he conseguido encontrar el fallo, he revisado la forma en que se leen las imágenes y como se pasan los parámetros pero no consigo detectar el fallo.

**Comment by jmbuena** [comment]
Hola Jorge,

Si estás usando el detector de coches entrenado, este tiene que usarse con acfDetectBadaCost (el acfDetect sólo toma detectores entrenados con AdaBoost - con acfTrain -).

A ver si es eso ...
JM

**Comment by jmbuena** [comment]
Ya sabemos usar el detector BadaCost en Matlab.
