### ISSUE TITLE
Arreglar la carga del clasificador de disco desde un único fichero yaml

### ISSUE THREAD

**Issue by jmbuena** [RoboticsLabURJC/2017-tfm-jorge_vela#22]
Se trata de realizar lo siguiente:
  - Guardar todas las matrices y variables del clasificador en un único fichero yaml. Para ello habrá que generar un script Matlab que dado un detector, haga el guardado de todas esas variables en el mismo fichero. Este script matlab deberá guardarse en la carpeta matlab del proyecto y usar los scripts que hay ahí. Muy importante que se use el matlab2opencv.m qua hay en la carpeta (de esta forma funcionará el readMatrixFromFileNode que hay en Utils.
  - Arreglar el BadacostDetector::load y ChannelsPyramid::load para que solo se carguen las variables del clasificador en la clase BadacostDetector. A ChannelsPyramid y resto de clases que necesitan variables del clasificador se les pasarán estos datos.

Habrá que modificar los tests de prueba de BadacostDetector para que funcionen con coches y también probar el de caras que hay en [el siguiente repo](https://github.com/jmbuena/toolbox.badacost.faces.public/tree/master/FACES_DETECTION_EXPERIMENTS/BADACOST_1_1.500000e%2B00_1_D_6_T_1024_N_10000_NA_40000).

**Comment by jorgevelap** [comment]
He subido un fichero llamado clf2yml.m, el cual coge los datos que se utilizan del detector y los guarda en un fichero .yml. De la forma que lo he hecho, llama a matlab2opencv.m que es un poco variado. Ya que solo hace la transpuesta de la matriz cuando se trata de Cprime. Al realizar las pruebas llamando a este clasificador no dan error.

En ChannelsPyramid está comentada la función load, cargando todos los datos desde BadacostDetector para ver si así funciona, y parece que las pruebas las pasa correctamente.
