### ISSUE TITLE
Implementar clase ChannelFeatureExtractor y derivadas ...

### ISSUE THREAD

**Issue by jmbuena** [RoboticsLabURJC/2017-tfm-jorge_vela#4]
Necesitamos construir la parte de más bajo nivel de extracción de los canales de Piotr Dollar. Estos son:
   - Tres canales de color: LUV (es un espacio de color).
   - 1 Canal con la magnitud del gradiente.
   - N canales con la detección debordes en cada píxel utilizando diferentes orientaciones (p.ej. respuesta a un flitro de derivada en vertical, uno de derivada en horizontal, otro a -45º y un cuarto a 45º.

Dollar define N=6, pero deberíamos dejarlo abierto al número que necesite el que entrenó un detector.

La clase ChannelFeatureExtractor, por tanto, debe definir la interfaz de todos los algoritmos de extracción de características. En ellos entra una imagen y pueden salir varios canales (imágenes Float o uint8) con el resultado de varios filtrados. 

Deberíamos tener un método principal como:

      std::vector<cv::Mat> ChannelFeaturesExtractor::extractFeatures(cv::Mat img);

Y en las clases derivadas, implementarlo:
   
  -  ChannelsLUVExtractor::extractFeatures
  - ChannelsGradientMagnitudeExtractor::extractFeatures
  - ChannelsHoGExtractor::extractFeatures

Si lo hacemos de esta manera podremos más adelante añadir otras características fácilmente. 

Es importante escribir un programa de test para cada tipo de características. Estos tests deberían poder ejecutarse automáticamente, por ejemplo, utilizando [GoogleTests](https://github.com/google/googletest). La idea de un test en este caso sería:
   - Tener un directorio de imágenes y su versión procesada (canales calculados) con el framework de Matlab.
   - El test lee una imagen de disco, lee su versión procesada para el tipo de clase derivada de ChannelsFeatureExtractor que toque y ejecuta extractFeatures sobre la imagen original. Después se compara la diferencia de imágenes (procesada en C++ y Matlab) y se calcula la diferencia de valores de píxeles promedio y la máxima diferencia. Ambas deben de estar por debajo de un umbral para pasar el test.

**Comment by jorgevelap** [comment]
He estado durante estos días por un lado la realización del código en c++. Para empezar con esto he planteado un programa con la finalidad de realizar las distintas clases con el extractor de características como me indicaste. 
Durante la realización del código me han surgido las siguientes dudas:
Para obtener las imágenes LUV hay una función con OpenCV que se supone que te retorna está imagen, de donde ya se pueden extraer los diferentes canales, pero los valores obtenidos no son iguales a los que deberían salir utilizando las expresiones matemáticas, por lo tanto no se si estoy utilizando mal la función, he entendido mal como extraer dichos colores o cual es el fallo.

Por otro lado, con respecto a la detección de bordes también me han surgido dudas. He estado mirando las diferentes funciones de OpenCV, pero para los bordes en 45 grados hay que realizar todo el proceso matemático que se realiza en  hough no? ¿Se hace así para todas las direcciones? He estado realizando pruebas pero no he obtenido resultados óptimos por el momento.


No he podido subir nada al repositorio donde estamos trabajando, me ha dado un error de permisos. Por si acaso las pruebas que he estado haciendo están en el siguiente enlace:

https://github.com/jorgevelap/2017-tfm-jorge_vela

**Comment by jmbuena** [comment]
Ya están correctamente implementados los ChannelsExtractors de todos los canales ACF.
