### ISSUE TITLE
Utilizando directamente las clases de pdollar

### ISSUE THREAD

**Issue by jorgevelap** [RoboticsLabURJC/2017-tfm-jorge_vela#5]
Estoy intentando comprender el código de pdollar. Intentando directamente coger las clases que contiene https://github.com/pdollar/toolbox/tree/master/channels y utilizándolas. No consigo hacerlas funcionar, ya que por ejemplo, para el resample, dándole una imagen y esperando a obtener la salida me ocurre lo siguiente:

![Captura](https://user-images.githubusercontent.com/16937271/58579642-d0474300-824b-11e9-9207-37f1ca5fcc85.PNG)
![Captura_2](https://user-images.githubusercontent.com/16937271/58579643-d0dfd980-824b-11e9-84f2-d09fea6b78bc.PNG)

La primera es la imagen de entrada y la segunda la que obtengo tras el resample. Para llamar a esta función lo hago con la siguiente línea:

resample(buffer,imgRes,height1,height1,width1,width1,d_test,1.0f);

los tamaños en todos los casos son el ancho y el alto de las fotos, d_test el numero de canales, que al ser en escala de grises es 1. El tamaño de la imagen el mismo que el de la imagen de entrada.

Subiré el código de algún ejemplo que he intentado.

Muchas gracias.

**Comment by jmbuena** [comment]
Hola,
Lo que hablamos la otra vez era centrarnos en la función [chnsCompute](https://github.com/pdollar/toolbox/blob/master/channels/chnsCompute.m), que calcula las características que se utilizan en el detector. La idea es comparar lo que de esta función con lo que salga de la implementación directa en C++ usando[ la parte en C++ que ya tiene Dollar](https://github.com/pdollar/toolbox/tree/master/channels/private) para el cálculo de características. 

En el caso concreto de resample no se si estará bien implementada la función o ese es el uso para el que está pensada. ¿Has probado a hacerlo con un resample a tamaños diferentes?

**Comment by jorgevelap** [comment]
Hola,
Si estoy intentando utilizar las funciones de chnsCompute, para este caso el resample es el de imResampleMex.cpp. No se si estoy fallando al pasar la imagen a un buffer de tipo float y luego volverla a convertir a cv::Mat para mostrarla.

  resample(buffer,convT,height1,height1,width1,width1,d_test,1.0f);
  cv::Mat dummy_query_2 = cv::Mat(128,128, CV_8UC1, convT);

La imagen se distorsiona mas cuantos mas escala pongo, a continuación muestro la imagen multiplicando por dos el tamaño de la imagen de salida.

![Captura_3](https://user-images.githubusercontent.com/16937271/58746735-03631f80-8462-11e9-8aa2-810428e854af.PNG)

**Comment by jmbuena** [comment]
Entonces creo que el problema es que en las matrices de Matlab, el buffer lineal que guarda los datos va por columnas y el de OpenCV (cv::Mat) va por filas. Así que habrá que trasponer la matriz de matlab para que el buffer sea adecuado para el cv::Mat.

JM.

**Comment by jorgevelap** [comment]
He continuado con lo que me comentaste pero no consigo obtener nada, voy a seguir trabajando en ello pero he subido el código por si se puede detectar el fallo.
En el ejemplo que adjunto a continuación, lo único que hago es coger su ejemplo de la función imPad y cambiar el array que el crea por una imagen real, pero se obtiene la imagen distorsionada.
Voy a seguir trabajando en ello a ver si consigo detectar el error.

https://github.com/RoboticsURJC-students/2017-tfm-jorge_vela/blob/master/chnsTest/newChnsTest.cpp


Muchas gracias.

**Comment by jorgevelap** [comment]
La función resample ya existe en la clase Utils, los tests se han realizado y funcionan correctamente. Por ello, se cierra este hilo.
