### ISSUE TITLE
Añadir extracción de canales del gradiente: ChannelsExtractorGradHist

### ISSUE THREAD

**Issue by jmbuena** [RoboticsLabURJC/2017-tfm-jorge_vela#7]
Aquí añadiríamos lo que se hace en el siguiente código Matlab de [chnsCompute.m](https://github.com/pdollar/toolbox/blob/e87332637bbe8e8b92dd487c87567d9628404523/channels/chnsCompute.m#L162):

```
p=pChns.pGradHist; nm='gradient histogram';
if( p.enabled )
  binSize=p.binSize; if(isempty(binSize)), binSize=shrink; end
  H=gradientHist(M,O,binSize,p.nOrients,p.softBin,p.useHog,p.clipHog,full);
  chns=addChn(chns,H,nm,pChns.pGradHist,0,h,w);
end
```
Así que necesitaríamos llamar a [gradientHist.m ](https://github.com/pdollar/toolbox/blob/master/channels/gradientHist.m) que a su vez llama a [gradientMex.cpp](https://github.com/pdollar/toolbox/blob/master/channels/private/gradientMex.cpp).

**Comment by jorgevelap** [comment]
Estoy teniendo problemas al trabajar con la clase ChannelsExtractorGradHist.
No consigo obtener los mismos resultados con Matlab y con c++. He probado a poner los mismos parámetros ( H = gradientHist( M, O, [binSize,nOrients,softBin,useHog,clipHog,full] ) ) en ambos casos y siempre da diferentes resultados.  
Revisando el código, he visto que cuando llama a la funcion gradHist antes llama a esta funcion:
pl[0] = mxCreateMatrix3(hb,wb,nChns,mxSINGLE_CLASS,1,(void**)&H);
en la que se modifica la H, pero esa función la hace el para cuando vienen los datos de matlab.

Voy a seguir mirando a ver si encuentro el problema / solución, pero no veo que mas puede estar pasando o como resolverlo.

Es el ultimo paso que queda para tener chnsCompute terminado, ya que los anteriores problemas están solucionados.

Muchas gracias.

**Comment by jorgevelap** [comment]
Primeras pruebas de chnsCompute realizadas.
El problema principal era que la orientación del gradiente variaba en una parte para este caso, al arreglarlo los test continuaban saliendo bien y ya se obtiene la misma M,O,H y la imagen LUV igual que en matlab.

**Comment by jmbuena** [comment]
¡Fenomenal!

**Comment by jmbuena** [comment]
Ya tenemos la extracción de canales de gradiente funcionando.
