### ISSUE TITLE
ChnsPyramid

### ISSUE THREAD

**Issue by jorgevelap** [RoboticsLabURJC/2017-tfm-jorge_vela#9]
Trabajando con chnsPyramid, y por lo que veo, hay puntos en los que utiliza la estructura creada para devolver los valores con los que ha trabajado.

https://github.com/pdollar/toolbox/blob/master/channels/chnsPyramid.m

En la linea 175 que ejecuta lo siguiente:

  for j=1:nTypes, ratio=(scales(i)/scales(iR)).^-lambdas(j);
    data{i,j}=imResampleMex(data{iR,j},sz1(1),sz1(2),ratio); end

llama a ese data, por lo que entiendo hay que crear la estructura de chnsCompute y aquí también verdad?

Gracias.

**Comment by jorgevelap** [comment]
Me he fijado y he visto que lo que utiliza de la estructura son los canales, por lo que se puede seguir trabajando con lo que teníamos que retornaba chnsCompute

**Comment by jmbuena** [comment]
Si. Eso es, en el data{i,j} lo que tiene son los canales. Va aproximando unos canales intermedios en base a los otros.

**Comment by jmbuena** [comment]
Hemos implementado correctamente ChnsPyramid al menos para la versión que llama a ImResample + extractChannels para todas las escalas (sin aproximaciones). Ver commits aaab23474d8175dcbc68cbe980a04c180f3c4712,  aea9aa58cd21492fa8f4c0395557b83ae2e22643 y e31403b1c99937864a5473ca8343cccab4dbc1d6.
